package com.assignmentException;

//WAP to check what happen when Exception is thrown by main method
public class Q13MainExceptionExample {

	public static void main(String[] args) {
		throw new RuntimeException("Exception thrown from main method");
	}
}
